IF EXISTS (SELECT 1 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_TYPE='BASE TABLE' 
           AND TABLE_NAME='STOCK_HIST_DATA') 
		   
BEGIN
DROP TABLE STOCK_HIST_DATA
END

CREATE TABLE [dbo].[STOCK_HIST_DATA](
    [STOCKCODE] [varchar](6) NOT NULL,
    [DATET] [varchar](20) NOT NULL,
    [TRANSACTVOLUME] [varchar](20) NULL,
    [TOTALPRICE] [varchar](20) NULL,
    [STARTPRICE] [varchar](20) NULL,
    [HIGHESTPRICE] [varchar](20) NULL,
    [LOWESTPRICE] [varchar](20) NULL,
    [ENDPRICE] [varchar](20) NULL,
    [UPANDDOWN] [varchar](20) NULL,
    [SHARESTRADENUM] [varchar](20) NULL,
    PRIMARY KEY CLUSTERED
(
    [STOCKCODE] ASC,
[DATET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]