IF EXISTS (SELECT 1 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_TYPE='BASE TABLE' 
           AND TABLE_NAME='STOCKTYPE_CODE') 
		   
BEGIN
DROP TABLE STOCKTYPE_CODE
END

CREATE TABLE STOCKTYPE_CODE (
STOCKCODE varchar(10) NOT NULL ,
STOCKNAME nvarchar(30) NOT NULL,
TYPE nvarchar(20) NOT NULL
primary key (STOCKCODE)
)
CREATE INDEX IDX_STOCKTYPE_CODE
ON STOCKTYPE_CODE (STOCKCODE, STOCKNAME);

CREATE INDEX IDX_STOCK_HIST_DATA
ON STOCK_HIST_DATA (STOCKCODE, DATET);