server:
  port: 8082
  debug: true
spring:
  config:
    import: "classpath:db.properties"
#  security:
#    user:
#      name: "lizuan"
#      password: "$2a$10$1txmqJynoBEx3YDRT1bDJOrCRwXosykEv8ZhzSK5yUuDmldv68o/a"
      # "Mars@@@7811"
logging:
  config: 'src/main/resources/logback.xml'
  level:
    root: info
#  security:
#    oauth2:
#      resource:
#        filter-order: 3
#       jwk:
#          key-set-uri: http://auth-server:8090/oauth2/keys