IF EXISTS (SELECT 1 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_TYPE='BASE TABLE' 
           AND TABLE_NAME='USERTB') 
		   
BEGIN
DROP TABLE USERTB
END

IF EXISTS (SELECT 1 
           FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_TYPE='BASE TABLE' 
           AND TABLE_NAME='USERROLE') 
		   
BEGIN
DROP TABLE USERROLE
END

CREATE TABLE USERTB (
ID int NOT NULL ,
USERNAME varchar(50) NOT NULL ,
PASSWORD varchar(200) NOT NULL ,
ENABLED int NOT NULL ,
ACCOUNTNONEXPIRED int NOT NULL ,
ACCOUNTNONLOKED int NOT NULL ,
CREDENTIALSNONEXPIRED int NOT NULL
primary key (ID)
)
CREATE INDEX IDX_USERTB
ON USERTB (ID,USERNAME);
	
	
	
CREATE TABLE USERROLE (
ID int NOT NULL ,
UID int NOT NULL ,
RID int NOT NULL ,
primary key (ID)
)
CREATE INDEX IDX_USERROLE
ON USERROLE (ID);



CREATE TABLE ROLE (
    ID int NOT NULL ,
    NAME NVARCHAR(32) NOT NULL ,
    NAME_ZH NVARCHAR(32) NOT NULL ,
    primary key (ID)
)
CREATE INDEX IDX_ROLE
    ON ROLE (ID);