CREATE TABLE OAUTHCLIENTDETAILS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    CLIENTID VARCHAR(255) NOT NULL UNIQUE,
    USERNAME VARCHAR(255),
    RESOURCESIDS VARCHAR(255) ,
    CLIENTSECRET VARCHAR(255) NOT NULL,
    SCOPE VARCHAR(255) NOT NULL,
    AUTHORIZEDGRANTTYPES VARCHAR(255) NOT NULL,
    WEBSERVERREDIRECTURIS VARCHAR(255) NOT NULL,
    AUTHORITIES VARCHAR(255),
    ACCESSTOKENVALIDITY INT DEFAULT 0,
    REFRESHTOKENVALIDITY INT DEFAULT 0,
    ADDITIONALINFORMATION VARCHAR(255),
    AUTOAPPROVE VARCHAR(255)
);

CREATE TABLE oauthclientdetails (
    id INT IDENTITY(1,1) PRIMARY KEY,
    clientid VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255),
    resourcesids VARCHAR(255) ,
    clientsecret VARCHAR(255) NOT NULL,
    scope VARCHAR(255) NOT NULL,
    authorizedgranttypes VARCHAR(255) NOT NULL ,
    webserverredirecturis VARCHAR(255) NOT NULL ,
    authorities VARCHAR(255),
    accesstokenvalidity INT DEFAULT 0,
    refreshtokenvalidity INT DEFAULT 0,
    additionalinformation VARCHAR(255),
    autoapprove VARCHAR(255)
);